Add support to fetch a SLA by API call
globocom/azkaban-cli pull request #36
Opened 2019-10-01 09:42 UTC by izontm

The code base is done, however I have some doubts about the expected output for the command.

2019-10-01 11:36 UTC, aguimaraesduarte commented
Hi @izontm thanks for the PR.
It looks good, but the tests for the new function is missing. Could you add it? [Here](https://github.com/globocom/azkaban-cli/tree/master/azkaban_cli/tests/test_azkaban) are the current tests that exist in the project, which you can use for inspiration :)

2019-10-01 12:17 UTC, aguimaraesduarte commented
@izontm You should also update the README with the command you are adding ;)

2019-10-01 14:00 UTC, izontm commented
My mistake, now I updated the README and did the tests.

2019-10-01 14:31 UTC, aguimaraesduarte requested changes

2019-10-01 14:31 UTC, aguimaraesduarte commented on azkaban_cli/azkaban_cli.py
> +        data = azkaban.fetch_sla(schedule)
You're capturing the response, but not doing anything with it (like logging it to the console).

The response will be something like this when it succeeds:
```{'slaEmails': ['my.email@test.company.com'], 'allJobNames': ['job_1, 'job_2, 'job_3'], 'settings': [{'duration': '300m', 'rule': 'SUCCESS', 'id': 'test_id', 'actions': ['EMAIL']}]}```

I suggest you add a parsing function that will parse the response and print (`logging.info`) the output in a more human-readable fashion.

Take a look at [this PR here](https://github.com/globocom/azkaban-cli/pull/37/files#diff-4f86e3e923f34200240a9d0374b9c2c7), where I implement something very similar to what you want. Let me know if you have any questions

2019-10-02 11:54 UTC, aguimaraesduarte approved these changes

2019-10-02 11:55 UTC, aguimaraesduarte commented
Looks good to me! @izontm thanks for contributing!

2019-10-02 11:56 UTC, merged